export type RenderMode = "DOM" | "Canvas" | "CSS";

export interface CursorMeta {
  id: number;
  slug: string;
  name: string;
  tag: RenderMode;
  desc: string;
  hint: string; // interaction hint shown on showcase page
}

export const CURSORS: CursorMeta[] = [
  {
    id: 1,
    slug: "flair-trail",
    name: "Flair Trail",
    tag: "DOM",
    desc: "Images scatter behind your cursor path",
    hint: "Move your cursor around",
  },
  {
    id: 2,
    slug: "magnetic",
    name: "Magnetic",
    tag: "DOM",
    desc: "Elements pull the cursor into orbit",
    hint: "Hover over the buttons",
  },
  {
    id: 3,
    slug: "ink-bleed",
    name: "Ink Bleed",
    tag: "DOM",
    desc: "Organic blobs bloom like ink on paper",
    hint: "Move your cursor around",
  },
  {
    id: 4,
    slug: "particle-burst",
    name: "Particle Burst",
    tag: "DOM",
    desc: "Velocity-biased dot explosions",
    hint: "Move fast for bigger bursts",
  },
  {
    id: 5,
    slug: "ghost-trail",
    name: "Ghost Trail",
    tag: "DOM",
    desc: "Echoes of your cursor linger behind",
    hint: "Move slowly to see the chain",
  },
  {
    id: 6,
    slug: "spotlight",
    name: "Spotlight",
    tag: "CSS",
    desc: "Your cursor reveals content in the dark",
    hint: "Move to reveal what's hidden",
  },
  {
    id: 7,
    slug: "ripple",
    name: "Ripple",
    tag: "DOM",
    desc: "Every click sends rings across the page",
    hint: "Click anywhere on the page",
  },
  {
    id: 8,
    slug: "text-trail",
    name: "Text Trail",
    tag: "DOM",
    desc: "Words dissolve in your wake",
    hint: "Move your cursor around",
  },
  {
    id: 9,
    slug: "smear",
    name: "Smear",
    tag: "Canvas",
    desc: "Paintbrush strokes that dry and fade",
    hint: "Click & drag to paint",
  },
  {
    id: 10,
    slug: "constellation",
    name: "Constellation",
    tag: "Canvas",
    desc: "Stars connect where you slow down",
    hint: "Move slowly to build star maps",
  },
  {
    id: 11,
    slug: "shockwave",
    name: "Shockwave",
    tag: "Canvas",
    desc: "Force field pushes a grid of particles",
    hint: "Move cursor to push particles",
  },
  {
    id: 12,
    slug: "dna-helix",
    name: "DNA Helix",
    tag: "DOM",
    desc: "Two strands weave perpendicular to motion",
    hint: "Move in smooth arcs",
  },
  {
    id: 13,
    slug: "neon-glow",
    name: "Neon Glow",
    tag: "Canvas",
    desc: "Light tubes burn and fade as you draw",
    hint: "Click & drag to draw light",
  },
  {
    id: 14,
    slug: "smoke",
    name: "Smoke",
    tag: "DOM",
    desc: "Soft wisps curl upward from your path",
    hint: "Move your cursor around",
  },
  {
    id: 15,
    slug: "wormhole",
    name: "Wormhole",
    tag: "Canvas",
    desc: "A vortex opens and swallows nearby dots",
    hint: "Hold cursor still to open a vortex",
  },
  {
    id: 16,
    slug: "typewriter",
    name: "Typewriter",
    tag: "DOM",
    desc: "Characters stamp as you sweep across",
    hint: "Move your cursor around",
  },
  {
    id: 17,
    slug: "aurora",
    name: "Aurora",
    tag: "Canvas",
    desc: "Wide ribbons of shifting colour trail you",
    hint: "Move slowly for wider ribbons",
  },
  {
    id: 18,
    slug: "shatter",
    name: "Shatter",
    tag: "DOM",
    desc: "Click to crack the screen into shards",
    hint: "Click anywhere to shatter",
  },
  {
    id: 19,
    slug: "liquid-mercury",
    name: "Liquid Mercury",
    tag: "Canvas",
    desc: "Metallic blobs merge and dissipate",
    hint: "Move your cursor around",
  },
  {
    id: 20,
    slug: "shadow-clone",
    name: "Shadow Clone",
    tag: "DOM",
    desc: "Five cursors fly in V-formation",
    hint: "Move in sweeping curves",
  },
  {
    id: 21,
    slug: "firefly",
    name: "Firefly",
    tag: "Canvas",
    desc: "Bioluminescent sparks drift toward your cursor",
    hint: "Move slowly to gather the swarm",
  },
  {
    id: 22,
    slug: "vine",
    name: "Vine",
    tag: "Canvas",
    desc: "A living vine grows and sprouts leaves",
    hint: "Sweep to grow longer stems",
  },
  {
    id: 23,
    slug: "raindrop",
    name: "Raindrop",
    tag: "Canvas",
    desc: "Drops fall and ripple where your trail lands",
    hint: "Move to spawn rain trails",
  },
  {
    id: 24,
    slug: "pollen",
    name: "Pollen",
    tag: "DOM",
    desc: "Pastel pollen motes drift on cursor wind",
    hint: "Move in arcs to fan the dust",
  },
  {
    id: 25,
    slug: "lava-lamp",
    name: "Lava Lamp",
    tag: "Canvas",
    desc: "Metaball blobs merge like molten lava",
    hint: "Move to tug the blobs around",
  },
  {
    id: 26,
    slug: "glitch",
    name: "Glitch",
    tag: "DOM",
    desc: "RGB scanline artifacts flicker in your wake",
    hint: "Move quickly for heavier distortion",
  },
  {
    id: 27,
    slug: "matrix-rain",
    name: "Matrix Rain",
    tag: "DOM",
    desc: "Neon glyph columns rain from your path",
    hint: "Sweep to spawn longer code streams",
  },
  {
    id: 28,
    slug: "circuit-trace",
    name: "Circuit Trace",
    tag: "Canvas",
    desc: "PCB-like traces route along a snapped grid",
    hint: "Move steadily to draw right-angle paths",
  },
  {
    id: 29,
    slug: "pixel-trail",
    name: "Pixel Trail",
    tag: "DOM",
    desc: "Retro pixel stamps pop and dissolve behind you",
    hint: "Move to paint an 8-bit trail",
  },
  {
    id: 30,
    slug: "hologram",
    name: "Hologram",
    tag: "Canvas",
    desc: "Interference rings and scanlines pulse at cursor",
    hint: "Move to emit holographic pulses",
  },
  {
    id: 31,
    slug: "confetti",
    name: "Confetti",
    tag: "DOM",
    desc: "Clicks burst colorful confetti explosions",
    hint: "Click anywhere to celebrate",
  },
  {
    id: 32,
    slug: "bubble-wrap",
    name: "Bubble Wrap",
    tag: "DOM",
    desc: "Bubbles inflate then pop along your trail",
    hint: "Move to pop more bubbles",
  },
  {
    id: 33,
    slug: "crayon",
    name: "Crayon",
    tag: "Canvas",
    desc: "Waxy crayon strokes blend with paper texture",
    hint: "Click and drag to draw",
  },
  {
    id: 34,
    slug: "stardust",
    name: "Stardust",
    tag: "DOM",
    desc: "Metallic star dust sparkles and fades away",
    hint: "Move to scatter glitter",
  },
  {
    id: 35,
    slug: "string",
    name: "String",
    tag: "Canvas",
    desc: "A physics string whips and hangs from cursor",
    hint: "Move fast to whip the tail",
  },
  {
    id: 36,
    slug: "blade",
    name: "Blade",
    tag: "DOM",
    desc: "Velocity slashes cut luminous strokes through space",
    hint: "Flick quickly for longer slashes",
  },
  {
    id: 37,
    slug: "void",
    name: "Void",
    tag: "Canvas",
    desc: "A dark void burns holes that slowly heal",
    hint: "Hover to deepen the void",
  },
  {
    id: 38,
    slug: "lightning",
    name: "Lightning",
    tag: "Canvas",
    desc: "Electric arcs jump across recent cursor points",
    hint: "Move in bursts to trigger bolts",
  },
  {
    id: 39,
    slug: "comet",
    name: "Comet",
    tag: "Canvas",
    desc: "A glowing comet head drags a long tail",
    hint: "Sweep to bend the trail",
  },
  {
    id: 40,
    slug: "mirror",
    name: "Mirror",
    tag: "DOM",
    desc: "A mirrored ghost cursor reflects across center",
    hint: "Move to control both cursors",
  },
];

export const TAG_COLORS: Record<RenderMode, string> = {
  DOM: "rgba(99,210,255,0.12)",
  Canvas: "rgba(255,160,100,0.12)",
  CSS: "rgba(160,255,130,0.12)",
};

export const TAG_TEXT: Record<RenderMode, string> = {
  DOM: "#63d2ff",
  Canvas: "#ffa064",
  CSS: "#a0ff82",
};
